SyoSil ApS UVM Scoreboard: cl_syoscb_hash_item Class Reference
cl_syoscb_hash_item Class Reference
A utility class used to wrap cl_syoscb_item objects when when using hash queues.
Inherits uvm_object, and uvm_object.
Public Member Functions
virtual cl_syoscb_item get_item (int unsigned idx=0)
Item API: Returns an item from this hash item's queue If called without parameters, returns the first item from the queue If idx is not a valid index in the queue, raises a UVM_WARNING and returns null
virtual void add_item (cl_syoscb_item item)
Item API: Adds an item to this hash item
virtual int unsigned get_size ()
Item API: Returns the number of items stored in this hash item
virtual void delete_item (int unsigned idx=0)
Item API: Deletes an item from this hash item
Private Attributes
cl_syoscb_item items [$]
Queue of cl_syoscb_item with the same hash.
Detailed Description
A utility class used to wrap cl_syoscb_item objects when when using hash queues.
In case of a hash collision, this class contains a queue of all items with the same hash
Definition at line 3 of file cl_syoscb_hash_item.svh.
Member Function Documentation
add_item()
void cl_syoscb_hash_item::add_item (cl_syoscb_item item) virtual
Item API: Adds an item to this hash item
Parameters
item The item to add
Definition at line 52 of file cl_syoscb_hash_item.svh.
References items.
Referenced by cl_syoscb_hash_aa_wrapper< HASH_DIGEST_WIDTH >::insert().
delete_item()
void cl_syoscb_hash_item::delete_item (int unsigned idx = 0) virtual
Item API: Deletes an item from this hash item
Parameters
idx The index of the item to delete. If index is out range, generates a UVM_ERROR
Definition at line 65 of file cl_syoscb_hash_item.svh.
References items.
Referenced by cl_syoscb_hash_aa_wrapper< HASH_DIGEST_WIDTH >::delete().
get_item()
cl_syoscb_item cl_syoscb_hash_item::get_item (int unsigned idx = 0) virtual
Item API: Returns an item from this hash item's queue If called without parameters, returns the first item from the queue If idx is not a valid index in the queue, raises a UVM_WARNING and returns null
Parameters
idx The index to access. Defaults to 0
Returns
The item at that index, or null if no items exist / the index is invalid
Definition at line 39 of file cl_syoscb_hash_item.svh.
References items.
Referenced by cl_syoscb_hash_aa_wrapper< HASH_DIGEST_WIDTH >::get_item().
The documentation for this class was generated from the following files:
cl_syoscb_hash_item.svh
pk_syoscb.sv
Project: SyoSil ApS UVM Scoreboard, Revision: 1.0.3.0
Copyright 2014-2022 SyoSil ApS
All Rights Reserved Worldwide
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Doxygen Version: 1.8.14
Generated with IDV SV Filter Version: 2.6.3
Fri Sep 2 2022 14:41:05
Find a documentation bug? Report bugs to: scoreboard@syosil.com