SyoSil ApS UVM Scoreboard: cl_syoscb_queue_iterator_base Class Reference
cl_syoscb_queue_iterator_base Class Reference
Queue iterator base class defining the iterator API used for iterating over queues.
Public Member Functions
virtual cl_syoscb_proxy_item_base next ()
Iterator API: Moves the iterator one step forward, returning the next item in the queue.
virtual bit has_next ()
Iterator API: Checks if there are more items in the queue in the forward direction
virtual int next_index ()
Iterator API: Returns the index of the item which would be returned if next() was called
virtual cl_syoscb_proxy_item_base previous ()
Iterator API: Moves the iterator one step backward, returning the previous item in the queue.
virtual bit has_previous ()
Iterator API: Checks if there are more items in the queue in the backward direction
virtual int previous_index ()
Iterator API: Returns the index of the item which would be returned if previous() was called
virtual bit first ()
Iterator API: Moves the iterator to the first item in the queue.
virtual bit last ()
Iterator API: Moves the iterator to the last item in the queue.
virtual bit set_queue (cl_syoscb_queue_base owner)
Iterator API: Sets the queue over which this iterator is iterating.
Protected Member Functions
virtual cl_syoscb_queue_base get_queue ()
Iterator API: Internal API: Returns the queue over which this iterator is iterating.
virtual cl_syoscb_proxy_item_base get_item_proxy ()
Iterator API: Internal API: Returns a proxy item that can be used to access the element that was just moved past by calling next or previous.
Protected Attributes
cl_syoscb_queue_base owner
The owner of this iterator.
int unsigned position = 0
Current position in the queue.
cl_syoscb_cfg cfg
Local handle to the SCB cfg.
Detailed Description
Queue iterator base class defining the iterator API used for iterating over queues.
The iterator API is modelled after the Java ListIterator interface https://docs.oracle.com/javase/8/docs/api/java/util/ListIterator.html. To iterate over all elements of a queue, use a while loop of the type
void'(iter.first());
while(iter.has_next()) begin
  cl_syoscb_proxy_item_base pib = iter.next();
  //do something
end
Internally, the iterator's position is always between elements. Calling next or previous will advance or reverse the iterator, returning the item that was moved past
items:              queue[0]   queue[1]   queue[2]   ...   queue[n-1]
cursor positions: ^          ^          ^          ^     ^            ^
Definition at line 17 of file cl_syoscb_queue_iterator_base.svh.
Member Function Documentation
first()
bit cl_syoscb_queue_iterator_base::first () virtual
Iterator API: Moves the iterator to the first item in the queue.
Calling has_previous at this point will always return 1'b0
Returns
1 if successful, 0 if the queue is empty
Reimplemented in cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_std, and cl_syoscb_queue_iterator_std.
Definition at line 104 of file cl_syoscb_queue_iterator_base.svh.
Referenced by cl_scb_test_iterator_unit_tests::check_first(), cl_scb_test_iterator_unit_tests::check_flush(), cl_syoscb_compare_base::create_primary_iterator(), cl_syoscb_queue_base::dump_orphans_to_file(), cl_syoscb_queue_base::dump_orphans_to_stdout(), cl_syoscb_compare_ooo::get_count_producer(), cl_syoscb_compare_iop::get_count_producer(), cl_syoscb_compare_ooo::primary_loop_do(), cl_syoscb_compare_io_2hp::primary_loop_do(), cl_syoscb_compare_iop::primary_loop_do(), cl_syoscb_compare_io::secondary_loop_do(), and cl_syoscb_compare_iop::secondary_loop_do().
get_item_proxy()
cl_syoscb_proxy_item_base cl_syoscb_queue_iterator_base::get_item_proxy () protected virtual
Iterator API: Internal API: Returns a proxy item that can be used to access the element that was just moved past by calling next or previous.
Returns
A proxy item for the element that was moved past.
Reimplemented in cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_std, and cl_syoscb_queue_iterator_std.
Definition at line 143 of file cl_syoscb_queue_iterator_base.svh.
get_queue()
cl_syoscb_queue_base cl_syoscb_queue_iterator_base::get_queue () protected virtual
Iterator API: Internal API: Returns the queue over which this iterator is iterating.
Returns
A handle to the queue. Raises a UVM_FATAL if no queue is associated with the iterator.
Definition at line 119 of file cl_syoscb_queue_iterator_base.svh.
References owner.
Referenced by cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::get_item_proxy(), cl_syoscb_queue_iterator_std::has_next(), cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::has_next(), cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::has_previous(), cl_syoscb_queue_iterator_std::next(), cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::next(), cl_syoscb_queue_iterator_std::previous(), and cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::previous().
has_next()
bit cl_syoscb_queue_iterator_base::has_next () virtual
Iterator API: Checks if there are more items in the queue in the forward direction
Returns
1 if there are more items in the forward direction, 0 otherwise (either empty queue or past last item)
Reimplemented in cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_std, and cl_syoscb_queue_iterator_std.
Definition at line 69 of file cl_syoscb_queue_iterator_base.svh.
Referenced by cl_scb_test_iterator_unit_tests::check_flush(), cl_scb_test_iterator_unit_tests::check_next(), cl_scb_test_iterator_unit_tests::check_prev(), cl_syoscb_queue_base::dump_orphans_to_file(), cl_syoscb_queue_base::dump_orphans_to_stdout(), cl_syoscb_compare_ooo::primary_loop_do(), cl_syoscb_compare_iop::primary_loop_do(), and cl_syoscb_compare_iop::secondary_loop_do().
has_previous()
bit cl_syoscb_queue_iterator_base::has_previous () virtual
Iterator API: Checks if there are more items in the queue in the backward direction
Returns
1 if there are more items in the backward direction, 0 otherwise (either empty queue or at first item)
Reimplemented in cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_std, and cl_syoscb_queue_iterator_std.
Definition at line 90 of file cl_syoscb_queue_iterator_base.svh.
Referenced by cl_scb_test_iterator_unit_tests::check_flush(), and cl_scb_test_iterator_unit_tests::check_prev().
last()
bit cl_syoscb_queue_iterator_base::last () virtual
Iterator API: Moves the iterator to the last item in the queue.
Calling has_next at this point will always return 1'b0.
Returns
1 if succesful, 0 if there is no first item (queue is empty)
Reimplemented in cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_std, and cl_syoscb_queue_iterator_std.
Definition at line 112 of file cl_syoscb_queue_iterator_base.svh.
Referenced by cl_scb_test_iterator_unit_tests::check_flush(), and cl_scb_test_iterator_unit_tests::check_last().
next()
cl_syoscb_proxy_item_base cl_syoscb_queue_iterator_base::next () virtual
Iterator API: Moves the iterator one step forward, returning the next item in the queue.
Returns
The next item if successful, raises a uvm_error if there is no next item
Reimplemented in cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_std, and cl_syoscb_queue_iterator_std.
Definition at line 62 of file cl_syoscb_queue_iterator_base.svh.
Referenced by cl_scb_test_iterator_unit_tests::check_first(), cl_scb_test_iterator_unit_tests::check_flush(), cl_scb_test_iterator_unit_tests::check_prev(), cl_syoscb_queue_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::delete_item(), cl_syoscb_queue_base::dump_orphans_to_file(), cl_syoscb_queue_base::dump_orphans_to_stdout(), cl_syoscb_compare_ooo::get_count_producer(), cl_syoscb_compare_iop::get_count_producer(), cl_syoscb_compare_ooo::primary_loop_do(), cl_syoscb_compare_io::primary_loop_do(), cl_syoscb_compare_io_2hp::primary_loop_do(), cl_syoscb_compare_iop::primary_loop_do(), cl_syoscb_compare_io::secondary_loop_do(), and cl_syoscb_compare_iop::secondary_loop_do().
next_index()
int cl_syoscb_queue_iterator_base::next_index () virtual
Iterator API: Returns the index of the item which would be returned if next() was called
Returns
The index of the next item, or queue.size() if the iterator has reached the }.
Definition at line 76 of file cl_syoscb_queue_iterator_base.svh.
References position.
Referenced by cl_scb_test_iterator_unit_tests::check_flush(), cl_scb_test_iterator_unit_tests::check_last(), cl_scb_test_iterator_unit_tests::check_next(), cl_scb_test_iterator_unit_tests::check_prev(), cl_syoscb_queue_base::dump_orphans_to_file(), cl_syoscb_queue_base::dump_orphans_to_stdout(), cl_syoscb_compare_ooo::primary_loop_do(), cl_syoscb_compare_iop::primary_loop_do(), and cl_syoscb_compare_iop::secondary_loop_do().
previous()
cl_syoscb_proxy_item_base cl_syoscb_queue_iterator_base::previous () virtual
Iterator API: Moves the iterator one step backward, returning the previous item in the queue.
Returns
The previous item if successful, raises a uvm_error if there is no previous item
Reimplemented in cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_std, and cl_syoscb_queue_iterator_std.
Definition at line 82 of file cl_syoscb_queue_iterator_base.svh.
previous_index()
int cl_syoscb_queue_iterator_base::previous_index () virtual
Iterator API: Returns the index of the item which would be returned if previous() was called
Returns
The index of the previous item, or -1 if the iterator is pointing to the first item of the queue
Definition at line 97 of file cl_syoscb_queue_iterator_base.svh.
References position.
Referenced by cl_scb_test_iterator_unit_tests::check_first(), cl_scb_test_iterator_unit_tests::check_flush(), cl_scb_test_iterator_unit_tests::check_next(), cl_scb_test_iterator_unit_tests::check_prev(), cl_syoscb_queue_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::delete_item(), cl_syoscb_queue_base::dump_orphans_to_file(), cl_syoscb_queue_base::dump_orphans_to_stdout(), and cl_syoscb_compare_iop::secondary_loop_do().
set_queue()
bit cl_syoscb_queue_iterator_base::set_queue (cl_syoscb_queue_base owner) virtual
Iterator API: Sets the queue over which this iterator is iterating.
If a queue has already been associated with this iterator, or the queue type does not match the iterator type, generates a UVM_ERROR message with id ITER_ERROR.
Returns
1 if successful, raises a UVM_ERROR otherwise (a queue is already associated with this iterator, or wrong queue type)
Reimplemented in cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >, cl_syoscb_queue_iterator_std, and cl_syoscb_queue_iterator_std.
Definition at line 134 of file cl_syoscb_queue_iterator_base.svh.
Referenced by cl_scb_test_iterator_unit_tests::check_set_queue().
The documentation for this class was generated from the following files:
cl_syoscb_queue_iterator_base.svh
pk_syoscb.sv
Project: SyoSil ApS UVM Scoreboard, Revision: 1.0.3.0
Copyright 2014-2022 SyoSil ApS
All Rights Reserved Worldwide
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Doxygen Version: 1.8.14
Generated with IDV SV Filter Version: 2.6.3
Fri Sep 2 2022 14:41:11
Find a documentation bug? Report bugs to: scoreboard@syosil.com