SyoSil ApS UVM Scoreboard: cl_syoscb_proxy_item_base Class Reference
cl_syoscb_proxy_item_base Class Reference
Base class for all proxy items.
Public Member Functions
virtual cl_syoscb_item get_item ()
Item API: Get the scoreboard item that this proxy item represents
virtual void set_queue (cl_syoscb_queue_base queue)
Item API: Sets the queue that the referenced item belongs to
virtual cl_syoscb_queue_base get_queue ()
Item API: Gets the queue that this proxy item depends on
Detailed Description
Base class for all proxy items.
A proxy item is used to decouple the act of iterating over a queue from the queue's implementation. Proxy items encode information that specify where in a given queue a specific cl_syoscb_item can be found.
Definition at line 4 of file cl_syoscb_proxy_item_base.svh.
Member Function Documentation
get_item()
cl_syoscb_item cl_syoscb_proxy_item_base::get_item () virtual
Item API: Get the scoreboard item that this proxy item represents
Returns
That item
Definition at line 32 of file cl_syoscb_proxy_item_base.svh.
References cl_syoscb_queue_base::get_item().
Referenced by cl_syoscb_queue_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::delete_item(), cl_syoscb_queue_base::dump_orphans_to_file(), cl_syoscb_queue_base::dump_orphans_to_stdout(), cl_syoscb_queue_locator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::search(), cl_syoscb_queue_locator_std::search(), cl_syoscb_queue_locator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::validate_match(), and cl_syoscb_queue_locator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::validate_no_match().
get_queue()
cl_syoscb_queue_base cl_syoscb_proxy_item_base::get_queue () virtual
Item API: Gets the queue that this proxy item depends on
Returns
A handle to that queue
Definition at line 44 of file cl_syoscb_proxy_item_base.svh.
Referenced by cl_syoscb_queue_locator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::search().
set_queue()
void cl_syoscb_proxy_item_base::set_queue (cl_syoscb_queue_base queue) virtual
Item API: Sets the queue that the referenced item belongs to
Parameters
A handle to the queue
Definition at line 38 of file cl_syoscb_proxy_item_base.svh.
Referenced by cl_syoscb_queue_iterator_std::get_item_proxy(), cl_syoscb_queue_iterator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::get_item_proxy(), cl_syoscb_queue_locator_hash< pk_syoscb::MD5_HASH_DIGEST_WIDTH >::search(), and cl_syoscb_queue_locator_std::search().
The documentation for this class was generated from the following files:
cl_syoscb_proxy_item_base.svh
pk_syoscb.sv
Project: SyoSil ApS UVM Scoreboard, Revision: 1.0.3.0
Copyright 2014-2022 SyoSil ApS
All Rights Reserved Worldwide
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Doxygen Version: 1.8.14
Generated with IDV SV Filter Version: 2.6.3
Fri Sep 2 2022 14:41:06
Find a documentation bug? Report bugs to: scoreboard@syosil.com