SyoSil ApS UVM Scoreboard: cl_syoscb_compare Class Reference
cl_syoscb_compare Class Reference
Component which instantiates the chosen comparison algorithm.
Inherits uvm_component, and uvm_component.
Public Member Functions
void build_phase (uvm_phase phase)
UVM build phase: Gets the scoreboard's configuration and creates the comparison algorithm.
void extract_phase (uvm_phase phase)
UVM extract phase: Check if cl_syoscb_cfg::end_greediness is greedy.
virtual void compare_trigger (string queue_name="", cl_syoscb_item item=null)
Compare API: Starts a comparison by invoking the chosen compare strategy if comparisons are not disabled
virtual void compare_control (bit cc)
Compare API: Toggle comparisons on or off
Private Attributes
cl_syoscb_cfg cfg
Handle to the configuration.
cl_syoscb_compare_base compare_algo
Handle to the actual compare algorithm to be used.
Detailed Description
Component which instantiates the chosen comparison algorithm.
Serves to wrap the compare algorithm in a UVM component, as well as triggering additional comparisons at the end of the run phase if the greed level prescribes this.
Definition at line 4 of file cl_syoscb_compare.svh.
Member Function Documentation
compare_control()
void cl_syoscb_compare::compare_control (bit cc) virtual
Compare API: Toggle comparisons on or off
Parameters
cc compare control bit. If 1, comparisons are enabled, if 0, comparisons are disabled
Definition at line 71 of file cl_syoscb_compare.svh.
References compare_algo, and cl_syoscb_compare_base::compare_control().
Referenced by cl_syoscb::compare_control().
compare_trigger()
void cl_syoscb_compare::compare_trigger (string queue_name = "", cl_syoscb_item item = null) virtual
Compare API: Starts a comparison by invoking the chosen compare strategy if comparisons are not disabled
Parameters
queue_name Name of the queue which had an item inserted into it
item The scoreboard wrapper item that was inserted into the SCB
Definition at line 65 of file cl_syoscb_compare.svh.
References compare_algo, and cl_syoscb_compare_base::compare_trigger().
Referenced by cl_syoscb::compare_trigger().
extract_phase()
void cl_syoscb_compare::extract_phase (uvm_phase phase)
UVM extract phase: Check if cl_syoscb_cfg::end_greediness is greedy.
If yes, we want to drain all the remaining matches from the scb before moving to check_phase
Definition at line 56 of file cl_syoscb_compare.svh.
References cfg, compare_algo, cl_syoscb_compare_base::compare_main(), and cl_syoscb_cfg::get_end_greediness().
The documentation for this class was generated from the following files:
cl_syoscb_compare.svh
pk_syoscb.sv
Project: SyoSil ApS UVM Scoreboard, Revision: 1.0.3.0
Copyright 2014-2022 SyoSil ApS
All Rights Reserved Worldwide
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Doxygen Version: 1.8.14
Generated with IDV SV Filter Version: 2.6.3
Fri Sep 2 2022 14:41:01
Find a documentation bug? Report bugs to: scoreboard@syosil.com