SyoSil ApS UVM Scoreboard: cl_syoscb_cfg_pl Class Reference
cl_syoscb_cfg_pl Class Reference
Utility class for capturing the queue names associated with a producer.
Inherits uvm_object, and uvm_object.
Public Member Functions
virtual void set_list (string list[])
Sets the list of queue names associated with a producer.
virtual bit exists (string queue)
Checks whether a given queue is connected to the producer that this object represents.
Public Attributes
string list []
The list of queue names connected to the producer that this _pl represents.
Detailed Description
Utility class for capturing the queue names associated with a producer.
Definition at line 2 of file cl_syoscb_cfg_pl.svh.
Member Function Documentation
exists()
bit cl_syoscb_cfg_pl::exists (string queue) virtual
Checks whether a given queue is connected to the producer that this object represents.
Parameters
queue The name of the queue to check
Definition at line 39 of file cl_syoscb_cfg_pl.svh.
References list.
Referenced by cl_syoscb_cfg::exist_producer(), cl_syoscb_cfg::set_comparer(), and cl_syoscb_cfg::set_printer().
The documentation for this class was generated from the following files:
cl_syoscb_cfg_pl.svh
pk_syoscb.sv
Project: SyoSil ApS UVM Scoreboard, Revision: 1.0.3.0
Copyright 2014-2022 SyoSil ApS
All Rights Reserved Worldwide
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Doxygen Version: 1.8.14
Generated with IDV SV Filter Version: 2.6.3
Fri Sep 2 2022 14:41:01
Find a documentation bug? Report bugs to: scoreboard@syosil.com